/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JSplitPane;

import facade.DataFacade;
import model.Person;
import statePattern.State;

public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    JSplitPane splitPanel;
    Person person;
    boolean isAdmin = false;
    DataFacade dataFacade;
    
    Dashboard(JSplitPane splitPanel, Person p, DataFacade dataFacade) {
    	initComponents();
        this.splitPanel = splitPanel;
        this.person = p;
        this.dataFacade = dataFacade;
        
        if(p == null) {
        	isAdmin = true;
        }
        setData();
    }

    private void setData() {
    	btnAddPatient1.setVisible(isAdmin);
//    	btnViewPatient.setVisible(isAdmin);
	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnAddPatient1 = new javax.swing.JButton();
        btnViewPatient = new javax.swing.JButton();

        btnAddPatient1.setText("Add Patients");

        btnViewPatient.setText("View Patient Details");
        
        btnViewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientActionPerformed(evt);
            }
        });
        
        btnAddPatient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnAddPatient1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(btnViewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddPatient1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(295, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

//    private void btnViewPatientActionPerformed(java.awt.event.ActionEvent evt) {                                               
//        PatientDetails pd = new PatientDetails(splitPanel);
//        splitPanel.setRightComponent(pd);
//    } 
    
    private void btnViewPatientActionPerformed(java.awt.event.ActionEvent evt) {
    	if(isAdmin) {
	        ViewPatientDetails vp = new ViewPatientDetails(splitPanel, dataFacade);
	        splitPanel.setRightComponent(vp);
    	}else {
    		PatientDetails patientDetails = new PatientDetails(splitPanel, person);
    		splitPanel.setRightComponent(patientDetails);
    	}
    } 
    
    private void btnAddPatientActionPerformed(java.awt.event.ActionEvent evt) {
    	AddPatient ad = new AddPatient(splitPanel, dataFacade);
    	splitPanel.setBottomComponent(ad);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAddPatient1;
    private javax.swing.JButton btnViewPatient;
    // End of variables declaration                   
}
