package ui;

import javax.swing.JSplitPane;

import api.MedicalProcedureAPI;
import model.Person;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class PatientDetails extends javax.swing.JPanel {

    /**
     * Creates new form PatientDetails
     */
	JSplitPane splitPanel;
	Person person;
	
    public PatientDetails(JSplitPane splitPanel, Person person) {
    	this.splitPanel = splitPanel;
    	this.person = person;
        initComponents();
        setupData();
    }

    private void setupData() {
    	titleId.setText("" + person.getId());
    	lblName.setText(person.getFirstName());
    	lblLastName.setText(person.getLastName());
    	
    	MedicalProcedureAPI m = person.getMedicalBill(); 
    	System.out.println(m);
    	
    	
    	Boolean isToothPaste = m.getDesc().contains("Toothpaste"); 
    	checkBoxToothPaste.setSelected(isToothPaste);
    	
    	Boolean isTylenol = m.getDesc().contains("Tylenol"); 
    	checkBoxTylenol.setSelected(isTylenol);
    	
    	checkBoxXray.setSelected(true);
	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Id = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        titleId = new javax.swing.JLabel();
        FirstName = new javax.swing.JPanel();
        titleName = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        LastName = new javax.swing.JPanel();
        titleLastName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        MedicalServices = new javax.swing.JPanel();
        checkBoxMri = new javax.swing.JCheckBox();
        checkBoxXray = new javax.swing.JCheckBox();
        titleMedicalServices = new javax.swing.JLabel();
        Products = new javax.swing.JPanel();
        checkBoxTylenol = new javax.swing.JCheckBox();
        checkBoxToothPaste = new javax.swing.JCheckBox();
        titleProducts = new javax.swing.JLabel();
        lblPatient = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        lblId.setText("ID : ");

        javax.swing.GroupLayout IdLayout = new javax.swing.GroupLayout(Id);
        Id.setLayout(IdLayout);
        IdLayout.setHorizontalGroup(
            IdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IdLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(titleId, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        IdLayout.setVerticalGroup(
            IdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IdLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(IdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        titleName.setText("First Name : ");

        javax.swing.GroupLayout FirstNameLayout = new javax.swing.GroupLayout(FirstName);
        FirstName.setLayout(FirstNameLayout);
        FirstNameLayout.setHorizontalGroup(
            FirstNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FirstNameLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titleName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        FirstNameLayout.setVerticalGroup(
            FirstNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FirstNameLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(FirstNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        titleLastName.setText("Last Name : ");

        javax.swing.GroupLayout LastNameLayout = new javax.swing.GroupLayout(LastName);
        LastName.setLayout(LastNameLayout);
        LastNameLayout.setHorizontalGroup(
            LastNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LastNameLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titleLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        LastNameLayout.setVerticalGroup(
            LastNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LastNameLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(LastNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        checkBoxMri.setText("MRI");
        checkBoxMri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxMriActionPerformed(evt);
            }
        });

        checkBoxXray.setText("XRAY");
        checkBoxXray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxXrayActionPerformed(evt);
            }
        });

        titleMedicalServices.setText("Medical Services :");

        javax.swing.GroupLayout MedicalServicesLayout = new javax.swing.GroupLayout(MedicalServices);
        MedicalServices.setLayout(MedicalServicesLayout);
        MedicalServicesLayout.setHorizontalGroup(
            MedicalServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedicalServicesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(MedicalServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MedicalServicesLayout.createSequentialGroup()
                        .addComponent(titleMedicalServices, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(MedicalServicesLayout.createSequentialGroup()
                        .addComponent(checkBoxXray)
                        .addGap(40, 40, 40)
                        .addComponent(checkBoxMri)
                        .addGap(81, 81, 81))))
        );
        MedicalServicesLayout.setVerticalGroup(
            MedicalServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedicalServicesLayout.createSequentialGroup()
                .addComponent(titleMedicalServices, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(MedicalServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxXray)
                    .addComponent(checkBoxMri))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        checkBoxTylenol.setText("Tylenol");
        checkBoxTylenol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxTylenolActionPerformed(evt);
            }
        });

        checkBoxToothPaste.setText("ToothPaste");
        checkBoxToothPaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxToothPasteActionPerformed(evt);
            }
        });

        titleProducts.setText("Products");
        titleProducts.setToolTipText("");

        javax.swing.GroupLayout ProductsLayout = new javax.swing.GroupLayout(Products);
        Products.setLayout(ProductsLayout);
        ProductsLayout.setHorizontalGroup(
            ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ProductsLayout.createSequentialGroup()
                        .addComponent(checkBoxToothPaste)
                        .addGap(40, 40, 40)
                        .addComponent(checkBoxTylenol)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        ProductsLayout.setVerticalGroup(
            ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductsLayout.createSequentialGroup()
                .addComponent(titleProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxToothPaste)
                    .addComponent(checkBoxTylenol))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        lblPatient.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblPatient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatient.setText("Patient's Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MedicalServices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Products, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(lblPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPatient, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MedicalServices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Products, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>                        

    private void checkBoxMriActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void checkBoxXrayActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void checkBoxTylenolActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void checkBoxToothPasteActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  


    // Variables declaration - do not modify                     
    private javax.swing.JPanel FirstName;
    private javax.swing.JPanel Id;
    private javax.swing.JPanel LastName;
    private javax.swing.JPanel MedicalServices;
    private javax.swing.JPanel Products;
    private javax.swing.JCheckBox checkBoxMri;
    private javax.swing.JCheckBox checkBoxToothPaste;
    private javax.swing.JCheckBox checkBoxTylenol;
    private javax.swing.JCheckBox checkBoxXray;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JLabel titleId;
    private javax.swing.JLabel titleLastName;
    private javax.swing.JLabel titleMedicalServices;
    private javax.swing.JLabel titleName;
    private javax.swing.JLabel titleProducts;
    // End of variables declaration                   
}
